sudo: required
services:
  - redis-server
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r kinappserver/requirements.txt
  - pip install -r kinappserver/requirements_dev.txt
# command to run tests
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - make install-sdk; make install; make freeze; 
  - make test;
