sudo: required
services:
- redis-server
language: python
python:
- '3.6'
cache: pip
install:
- pip install -r tippicserver/requirements.txt
- pip install -r tippicserver/requirements_dev.txt
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
- make install-cv-module; make install-sdk; make install-travis;
- make test;