- cron:
    name: "release unclaimed goods every minute"
    job: "/opt/kin-app-server/kinappserver/cron/release_unclaimed_goods.sh"
  run_once: true # runs every minute, on one machine of the 2

- cron:
    name: "gather periodic db-stats"
    job: "/usr/bin/python3 /opt/kin-app-server/kinappserver/db_stats.py"
    # needs to run on all machines

- cron:
    name: "gather periodic xlm,kin balance"
    job: "/usr/bin/python3 /opt/kin-app-server/kinappserver/track_balance.py"
    # needs to run on all machines

- cron:
    name: "gather periodic data about missing txs"
    job: "/usr/bin/python3 /opt/kin-app-server/kinappserver/missing_txs.py"
  run_once: true # runs every minute, on one machine of the 2

- cron:
    name: "gather periodic metrics"
    job: "/usr/bin/python3 /opt/kin-app-server/kinappserver/metrics.py"
  run_once: true # runs every minute, on one machine of the 2

- cron:
    name: "send daily push messages"
    hour: 15
    minute: 0
    job: "/opt/kin-app-server/kinappserver/cron/send_engagement_push.sh"
  run_once: true # runs every date at 15 gmt

- cron:
    name: "replenish blackhawk cards"
    job: "/opt/kin-app-server/kinappserver/cron/replenish_blackhawk_cards.sh"
  run_once: true # runs every minute, on one machine of the 2

- cron:
    name: "periodically de-authenticate users"
    job: "/opt/kin-app-server/kinappserver/cron/deauth_users.sh"
  run_once: true # runs every minute, on one machine of the 2

- cron:
    name: "periodically track exceptions in the log"
    job: "/opt/kin-app-server/kinappserver/cron/track_exceptions.sh"
    minute: "*/5" # run every 5 minutes on all machines