- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install list of packages
  apt: name={{item}} state=installed
  with_items:
       - git

- name: Create /opt/payment-service
  file: path=/opt/payment-service state=directory


- name: Template payment-service config
  template:
    src=config/config.yml.j2
    dest=/opt/payment-service/config.yml

- name: Download eshu-backend
  get_url:
    url=https://s3.amazonaws.com/kinapp-deployment-binaries/eshu/eshu-backend-{{git_rev}}
    dest=/opt/eshu/eshu-backend
    force=yes
    mode=0770

- name: restart supervisor
  supervisorctl:
    name: eshu-backend
    state: restarted
