apps:

    - id: kinapp-beta # ios beta and android (both beta and release)
      numConsumers: 2
      amqpURI: amqp://admin:admin@eshu-rabbit-prod.kinitapp.com:5672/kinapp

      queue:
        exchangeName: eshu-exchange-beta
        exchangeType: direct
        queueName: eshu-queue-beta
        bindingKey: eshu-key-beta
        queueArgs:
          x-dead-letter-exchange: eshu-exchange-beta.dead
          x-max-priority: 2

      dispatcher:
        checkAppName: false

      feedback:
        numProducers: 1
        cacheSize: 100
        queue:
          exchangeName: eshu-feedback-exchange
          exchangeType: direct
          bindingKey: eshu-feedback-key
          reliable: true

      providers:
        enabled:
          - gcm
          - apns
        all:
          gcm:
            senderId: "{{ lookup('aws_ssm', '/config/prod/eshu/gcm-sender-id' )}}"
            apiKey: "{{ lookup('aws_ssm', '/config/prod/eshu/gcm-api-key' )}}"
            sandbox: false
            dryRun: false
            requestReceipts: false
            monitorConnection: true
            sendTimeout: 20
            debug: true
            circuitBreaker:
              tripFailures: 10
          apns:
            certFile: certs/Kinit-beta-kik.p12 # needs to be manually deployed
            password:
            sandbox: false
            topic: com.kik.kinit-beta
            circuitBreaker:
              tripFailures: 10

    - id: kinapp-release
      numConsumers: 2
      amqpURI: amqp://admin:admin@eshu-rabbit-prod.kinitapp.com:5672/kinapp

      queue:
        exchangeName: eshu-exchange-release
        exchangeType: direct
        queueName: eshu-queue-release
        bindingKey: eshu-key-release
        queueArgs:
          x-dead-letter-exchange: eshu-release-exchange.dead
          x-max-priority: 2

      dispatcher:
        checkAppName: false

      feedback:
        numProducers: 1
        cacheSize: 100
        queue:
          exchangeName: eshu-feedback-exchange
          exchangeType: direct
          bindingKey: eshu-feedback-key
          reliable: true

      providers:
        enabled:
          - apns
        all:
          apns:
            certFile: certs/Kinit-AppStore.p12 # needs to be manually deployed
            password:
            sandbox: false
            topic: org.kinecosystem.kinit
            circuitBreaker:
              tripFailures: 10
