- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-bin

  vars:
   deployment_env: stage
   environment_config:
     ENV: stage
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   debug: True
   nginx_domain: stage.kinitapp.com
   db_connstr: 'postgresql://kinappstageuser:password@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage'
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: 10.0.1.20
   stellar_timeout_sec: 10
   stellar_initial_account_balance: 10
   stellar_network: 'TESTNET'
   stellar_kin_issuer_address: GCKG5WGBIJP74UDNRIRDFGENNIH5Y3KBI5IHREFAJKV4MQXLELT7EX6V
   stellar_horizon_url: https://horizon-testnet.stellar.org/
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: False
   authentication_token_enabled: False
   p2p_transfers_enabled: True
   p2p_min_tasks: 1
   p2p_min_kin_amount: 500
   p2p_max_kin_amount: 3000

