- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-bin

  vars:
   environment_config:
     ENV: stage
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   debug: True
   nginx_domain: ec2-54-173-252-68.compute-1.amazonaws.com #kin-app-stage.rounds.video
   db_connstr: 'postgresql://kinappstageuser:password@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage'
   provider_endpoint: 'http://159.89.9.81:8545'
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   onboarding_service_base_url: 'ip-10-0-1-54.ec2.internal:8080'
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: 10.0.1.20
   stellar_base_seed: SBGEXBFFOJMHJHNNMIYS7KQT3LISQSEHNX2BYF6UFQZ4TSPWYXMWJRVV
   stellar_network: TESTNET
   stellar_channel_seeds: '"SDXG2Z2FVVJ6YIF5QI5EGN5DFIJXFR2G2VD6JWN3K6DWFSN7X5YVDRPM"'
   stellar_horizon_url: https://horizon-testnet.stellar.org/
