- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - franklinkim.environment
    - Datadog.datadog
    - kin-app-server

  vars:
   deployment_env: prod
   environment_config:
     ENV: prod
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   datadog_config:
     log_level: INFO
   debug: False
   nginx_domain: prod.kinitapp.com
   db_connstr: 'postgresql://kinappprod:password@kinappprod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappprod'
   redis_endpoint: 'kin-app-server-prod.qugi0x.ng.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: eshu-rabbit-prod.kinitapp.com
   stellar_timeout_sec: 10
   stellar_initial_account_balance: 10
   stellar_network: 'TESTNET'
   stellar_kin_issuer_address: GCKG5WGBIJP74UDNRIRDFGENNIH5Y3KBI5IHREFAJKV4MQXLELT7EX6V
   stellar_horizon_url: https://horizon-testnet.stellar.org/
   stellar_public_address: 'GCTH7N7X7T62JP7LBXUMZIY7ROI2U7XV42L2JNW7STCZQ5DIKXSOYOXR'
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'

