- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-bin

  vars:
   deployment_env: stage
   environment_config:
     ENV: stage
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   debug: True
   nginx_domain: stage.kinitapp.com
   db_connstr: 'postgresql://kinappstageuser:password@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage'
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: 10.0.1.20
   stellar_timeout_sec: 10
   stellar_initial_account_balance: 10
   stellar_base_seed: '' # leave empty if you use an encrypted key
   stellar_network: TESTNET
   stellar_kin_issuer_address: GCKG5WGBIJP74UDNRIRDFGENNIH5Y3KBI5IHREFAJKV4MQXLELT7EX6V
   stellar_channel_seeds: '"SCZEU7M63IL55UFSOTK66ECVMCN5RMY5BZ6E4R46ENR6GAG5NPAOHTXK","SB5ATB4X6ZRP6AUBNNKEZCBMHUUKAJENNH5P4YNMPTIIPYDIJZDQCZOG","SB32W4FMIQ4R6NM6XUVI3H3OXTO4FVP6EKHLBUJRZTT4IJSOKY2WTRLG","SCPVBPII4SPT2VSIQG5WEXBORSVVWYDVRK4T7CKS3MOASHFJYBNCNVAU","SCSO2LZHRZ2YWVLN6U7CX7LEGYOZZBTYOKDZ5U5MY7XZBIFNLHK5LBE6","SBWOKLAZC3PPLH2XXU2E5OAMZ75UWVUIOMCQ6AV3OFA44YMMCO3JREYW","SDCHIZGITVFLC4MPYZ257D2D2F6CYHW4HZ6SM7STEG26IU5KFGDLLM6G","SAC3HLY7D7LTQJWOIIAQVJB2TU5V44UZBRHHCJ7QQIV4Z44WVZ6R2QNG","SDDPMPEERFUU3TK5K7ATZ45MXIAN5ZBLRLRAMYCKTY3SIHJXFEU673FT","SC7WPMLEM54JUZNBUUFYUXSWMXROFHQ3L4TAXA7MJ2L7DYDWMIDP5UDD"' # leave empty if you use an encrypted key
   stellar_horizon_url: https://horizon-testnet.stellar.org/
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   stellar_base_seed_cipher_text_blob: 'AQIDAHhNi2+wi6LhNwRYR4UfKOaWqkHEzcCVcmTNoKpTpIuuGwHO5D8rdjR+YI7CVT2IUgl1AAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMs6YDEK/sIaV5qmesAgEQgCuCvmG12Gq+hDlgaY0gkn5AX4ohWHnhgMHr4uqpkE4KvWBMj6QVAhVCJEpN'
   encrypted_stellar_base_seed: 'gcjECQnEWu0m2am49w3Q6zo3Coh9k/vSKKBFRIH3pzRmF2oxXMu1m2zGswP4Rai4DoQuoELlJq9XqziDam8LgU7Eyp7GTdpDknEokV/BPzY='
   stellar_channel_seeds_cipher_text_blob: 'AQIDAHhNi2+wi6LhNwRYR4UfKOaWqkHEzcCVcmTNoKpTpIuuGwHJdjS4uqABQK3yOr9+5mMjAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1JtaqkFczAfjNTPlAgEQgCvVTzqkDuynj3ZHUo59wmCApDnFooxF0IAEE7zHdFm+Zbvm4l92q/kbLPrD'
   encrypted_stellar_channel_seeds: 'cbW+D7I1c3gpv58PpDYgYBg1QRg6eDbVUKpCvJIoel2f3u8Lkq+ub4frBKY8DI3FKCqqUjgtYDSebeLIJ9/nAMlmuyWwhIY5GJBhVKK6MLeVPIKcgZ8Q6F3/+nUk1FyuUQENqMhTmiPhKkFakUQVPagQDSvfrxIJueVLFJYUclbQO4auwWVGbg/GyLYtE7Dg6Zj296yHo0GdoHoJAB8z9vlttdZ1eIRxAeDm7i1YnuUXabx2StcGGZN7dHsPZrUFl6bLnG8JiKAApd2JhpmtlG5Y6rIO3H6d3UdlZfKpCtowv2MND6aVbicyuynuNAf1e90tn822ZLGkUcCc5/qX0Dznc2RpDRunhd2n2Lb9KCW5OPp8NRKrukj5kq1eBe0hDF/z5o/rGyJimKqmrk/+5M2AEhaFyw++smKDemm4Rml/cvaKwLYF+d8qEvtoUmjWch0wMzmIsTty0ZaqsIq1SlVBSCPesh1Ffe4Y5LKxgk1bylYuoEufpSa0vVP+bEOSLuypaphnxPs3N4ex9DQuTYNMQyULdhpZ7BxgxhBcMSBoiBlg8igUTrv4Tyky+/DCzuSe6TWourr78wZ99BxMzt4R0WPrXPhQF+RtMWVKAGDo6yV1vqayTYpnB6d458t9yVApzOSCoWMcb87QL5oKlr0j536y6Qy+XxdgnKGfPiEz4A9P+UKZX7cIeqf/DmMQtweEPrBRDDJD7wIoO3tmLevqN6qGQhP4m9FSc3RazYgyUwVFR5I+rJj2+t73MltV1ds7RSr9WQaR5LMiEiXHp1aaLXT7NXqZpfeqVTnIMXq7nX7kTIOkSKMGpdKcbd0d'


