- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true

  roles:
    - eshu-backend
    - Datadog.datadog

  vars:
    git_rev: e153ed6
    datadog_api_key: "cb6389daa2808d1c275f1f69bfff63e5"
    datadog_config:
      tags: "service:eshu-backend"
    env: STAGE
    target_name: eshu-backend
    log_level: debug

  vars_files:
    - vars/eshu-backend-stage.yml
