- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - franklinkim.environment
    - Datadog.datadog
    - kin-app-server

  vars:
   environment_config:
     ENV: stage
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   debug: True
   nginx_domain: ec2-54-173-252-68.compute-1.amazonaws.com #kin-app-stage.rounds.video
   db_connstr: 'postgresql://kinappstageuser:password@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage'
   provider_endpoint: 'http://159.89.9.81:8545'
   redis_endpoint: 'kinawardservicesync.pmvjly.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   onboarding_service_base_url: 'ip-10-0-1-54.ec2.internal'
