- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true

  roles:
    - eshu-backend
    - Datadog.datadog
    - igor_mukhin.bash_aliases

  vars:
    git_rev: e153ed6
    datadog_api_key: "{{ lookup('aws_ssm', '/config/stage/datadog/apikey' )}}"
    datadog_config:
      tags: "service:eshu-backend"
    env: STAGE
    target_name: eshu-backend
    log_level: debug
    bash_aliases:
      - { alias: '_env', command: 'echo "eshu stage"' }
      - { alias: '_grep', command: 'cat /var/log/supervisor/*|grep '}
      - { alias: '_log', command: 'cat /var/log/supervisor/*' }
      - { alias: '_tail', command: 'tail -f /var/log/supervisor/* -n 10' }

  vars_files:
    - vars/eshu-backend-stage.yml


