- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true

  roles:
    - eshu-backend
    - Datadog.datadog

  vars:
    git_rev: e153ed6
    datadog_api_key: "7d29689e7460c08f21128628adf11afd"
    datadog_config:
      tags: "service:eshu-backend"
    env: PROD
    target_name: eshu-backend
    log_level: debug

  vars_files:
    - vars/eshu-backend-prod.yml
