- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - franklinkim.environment
    - Datadog.datadog
    - kin-app-server
    - igor_mukhin.bash_aliases

  vars:
   deployment_env: prod
   environment_config:
     ENV: prod
   datadog_api_key: "cb6389daa2808d1c275f1f69bfff63e5"
   datadog_config:
     log_level: INFO
   debug: False
   nginx_domain: prod.kinitapp.com
   db_connstr: 'postgresql://kinappprod:password@kinappprod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappprod'
   redis_endpoint: 'kin-app-server-prod.qugi0x.ng.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: eshu-rabbit-prod.kinitapp.com
   stellar_timeout_sec: 10
   stellar_initial_account_balance: 10
   stellar_network: 'TESTNET'
   stellar_kin_issuer_address: GCKG5WGBIJP74UDNRIRDFGENNIH5Y3KBI5IHREFAJKV4MQXLELT7EX6V
   stellar_horizon_url: https://horizon-testnet.stellar.org/
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: False
   p2p_transfers_enabled: True
   p2p_min_tasks: 4
   p2p_min_kin_amount: 500
   p2p_max_kin_amount: 3000
   auth_token_send_interval_days: 1
   auth_token_enforced: False
   auth_token_enabled: True
   blackhawk_purchases_enabled: True
   blackhawk_critical_balance_threshold: 10 # no cards will be ordered when we reach this threshold
   bash_aliases:
     - { alias: 'log', command: 'cat /var/log/kinappserver.err.log' }
     - { alias: 'tail', command: 'tail -f /var/log/kinappserver.err.log -n 10' }
     - { alias: 'sql', command: 'psql postgresql://kinappprod:password@kinappprod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappprod'}
