- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - franklinkim.environment
    - Datadog.datadog
    - kin-app-server

  vars:
   deployment_env: prod
   environment_config:
     ENV: prod
   datadog_api_key: "7d29689e7460c08f21128628adf11afd"
   datadog_config:
     log_level: INFO
   debug: False
   nginx_domain: prod.kinitapp.com
   db_connstr: 'postgresql://kinappprod:password@kinappprod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappprod'
   redis_endpoint: 'kin-app-server-prod.qugi0x.ng.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: eshu-rabbit-prod.kinitapp.com
   stellar_timeout_sec: 10
   stellar_initial_account_balance: 10
   stellar_base_seed: 'SBKJRDZHJ7MTYDWD7ZACXIR22TYGYHJZTNF7CGJQKZBH2RLENFQCFYI5' # leave empty if you use an encrypted key
   stellar_network: 'CUSTOM'
   stellar_kin_issuer_address: GBOJSMAO3YZ3CQYUJOUWWFV37IFLQVNVKHVRQDEJ4M3O364H5FEGGMBH
   stellar_channel_seeds: '' # leave empty if you use an encrypted key
   stellar_horizon_url: https://horizon-kik.kininfrastructure.com/
   stellar_public_address: 'GBYNGCLKPGC5YLABEHAPVB4YKGME7TKP6PZ3MSW56BBQM2MMIPBK4KSJ'
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'

