- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    #- franklinkim.environment
    #- Datadog.datadog
    - kin-app-server
    #- igor_mukhin.bash_aliases

  vars:
   deployment_env: prod
   environment_config:
     ENV: prod
     STELLAR_ACCOUNT_SID: "{{ play_hosts.index(inventory_hostname) }}" # sets the host's index within the play
   datadog_api_key: "{{ lookup('aws_ssm', '/config/prod/datadog/apikey' )}}"
   datadog_config:
     log_level: INFO
     tags: "service:kin-app-server-prod"
   debug: False
   nginx_domain: api.kinitapp.com
   db_connstr: "postgresql://{{lookup('aws_ssm', '/config/prod/sql/userpassword')}}@kinitapp-prod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinitappprod"
   redis_endpoint: 'kinit-app-prod-001.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange # this is postfixed in the code with 'beta/release'
   eshu_queue: eshu-queue # this is postfixed in the code with 'beta/release'
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: eshu-rabbit-prod.kinitapp.com
   stellar_timeout_sec: 30
   stellar_initial_account_balance: 2 # = 20K txs, but 1.5 xlms are required for establishing trustline
   stellar_network: 'Public Global Kin Ecosystem Network ; June 2018'
   stellar_kin_issuer_address: GDF42M3IPERQCBLWFEZKQRK77JQ65SCKTU3CW36HZVCX7XX5A5QXZIVK
   stellar_horizon_url: https://horizon-ecosystem.kininfrastructure.com
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: True
   p2p_transfers_enabled: True
   p2p_min_tasks: 21
   p2p_min_kin_amount: 20
   p2p_max_kin_amount: 200
   auth_token_send_interval_days: 1
   auth_token_enforced: True
   auth_token_enabled: True
   blackhawk_purchases_enabled: True
   blackhawk_critical_balance_threshold: 30 # no cards will be ordered when we reach this threshold
   bash_aliases:
     - { alias: '_env', command: 'echo "kinappserver prod"' }
     - { alias: '_grep', command: 'cat /var/log/kinappserver.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/kinappserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/kinappserver.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/prod/sql/userpassword')}}@kinitapp-prod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinitappprod"}


# setup cron stuff that needs to run only on kin-app-server-prod-1
- hosts: kin-app-server-prod-1
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-cron


# add aliases to non-sudo user
- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: false
  roles:
    - igor_mukhin.bash_aliases

  vars:
   bash_aliases:
     - { alias: '_env', command: 'echo "kinappserver prod"' }
     - { alias: '_grep', command: 'cat /var/log/kinappserver.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/kinappserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/kinappserver.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/prod/sql/userpassword')}}@kinitapp-prod.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinitappprod"}
